### ISSUE TITLE
$.scrollbarWidth is not a function

### ISSUE THREAD

**Issue by hagaisela** [hashchange/jquery.isinview#1]
Hi,
I am getting this error when trying the plugin:
`jquery.isinview.js:241 Uncaught TypeError: $.scrollbarWidth is not a function(…)effectiveScrollbarWith @ jquery.isinview.js:241
getContainerScrollbarWidths @ jquery.isinview.js:936
getNetContainerWidth @ jquery.isinview.js:890
_isInView @ jquery.isinview.js:432
isInView @ jquery.isinview.js:336
$.fn.isInView @ jquery.isinview.js:83
BottomFadeHandler.onScroll @ bottomfadehandler.js:42
dispatch @ jquery.js:4435
elemData.handle @ jquery.js:4121`

**Comment by hashchange** [comment]
The plugin [depends on jQuery.documentSize](https://github.com/hashchange/jquery.isinview#dependencies-and-setup), which exposes `$.scrollbarWidth`. Load [jQuery.documentSize](https://github.com/hashchange/jquery.documentsize) first.
