### ISSUE TITLE
$('.foo .bar').not(':inViewport').each(... not working, returns all elements that match query

### ISSUE THREAD

**Issue by shock2provide** [hashchange/jquery.isinview#3]
While $('.foo .bar').filter(':inViewport').each(...) works just fine, when I try to select all hidden elements using $('.foo .bar').not(':inViewport').each(...) does not work as intended and all elements that match the '.foo .bar' query are returned...
Am I doing something wrong?

Thanks

**Comment by hashchange** [comment]
No, you didn't do anything wrong ... I did ;)

I'm surprised I didn't catch this earlier, but I've fixed it now and added tests to prevent a regression. Thank you!
